-- E-Ticaret Örnek Veri Seti (Otomatik Oluşturuldu)
-- Müşteri Verileri
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Ahmet', 'Yıldız', 'ahmet.yıldız86@ornekmail.com', 'Konya', 'Türkiye', '2023-02-21');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Hüseyin', 'Çelik', 'hüseyin.çelik62@ornekmail.com', 'Adana', 'Türkiye', '2023-07-05');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Hüseyin', 'Aydın', 'hüseyin.aydın1@ornekmail.com', 'Ankara', 'Türkiye', '2023-09-22');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Emre', 'Yıldız', 'emre.yıldız59@ornekmail.com', 'Gaziantep', 'Türkiye', '2024-06-05');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Fatma', 'Özdemir', 'fatma.özdemir13@ornekmail.com', 'Gaziantep', 'Türkiye', '2023-07-17');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Ali', 'Kılıç', 'ali.kılıç30@ornekmail.com', 'Antalya', 'Türkiye', '2023-10-12');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Hüseyin', 'Şahin', 'hüseyin.şahin18@ornekmail.com', 'Adana', 'Türkiye', '2024-06-06');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Zeynep', 'Aydın', 'zeynep.aydın94@ornekmail.com', 'Bursa', 'Türkiye', '2023-10-24');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Mustafa', 'Yılmaz', 'mustafa.yılmaz45@ornekmail.com', 'Antalya', 'Türkiye', '2023-04-19');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Fatma', 'Yılmaz', 'fatma.yılmaz15@ornekmail.com', 'Gaziantep', 'Türkiye', '2024-07-08');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Deniz', 'Demir', 'deniz.demir85@ornekmail.com', 'İzmir', 'Türkiye', '2023-11-06');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Canan', 'Şahin', 'canan.şahin93@ornekmail.com', 'Bursa', 'Türkiye', '2023-12-11');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Ayşe', 'Öztürk', 'ayşe.öztürk75@ornekmail.com', 'Konya', 'Türkiye', '2024-03-13');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Ali', 'Şahin', 'ali.şahin59@ornekmail.com', 'İzmir', 'Türkiye', '2023-10-29');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Deniz', 'Demir', 'deniz.demir73@ornekmail.com', 'İstanbul', 'Türkiye', '2024-06-15');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Ayşe', 'Kaya', 'ayşe.kaya19@ornekmail.com', 'Bursa', 'Türkiye', '2024-03-10');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Hüseyin', 'Şahin', 'hüseyin.şahin32@ornekmail.com', 'Ankara', 'Türkiye', '2023-03-01');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Ayşe', 'Öztürk', 'ayşe.öztürk61@ornekmail.com', 'Antalya', 'Türkiye', '2024-04-02');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Ahmet', 'Arslan', 'ahmet.arslan39@ornekmail.com', 'Gaziantep', 'Türkiye', '2023-02-01');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Cem', 'Demir', 'cem.demir73@ornekmail.com', 'Konya', 'Türkiye', '2024-03-03');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Emre', 'Kılıç', 'emre.kılıç85@ornekmail.com', 'İzmir', 'Türkiye', '2024-11-15');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Elif', 'Kaya', 'elif.kaya90@ornekmail.com', 'Adana', 'Türkiye', '2024-10-11');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Selin', 'Öztürk', 'selin.öztürk92@ornekmail.com', 'Konya', 'Türkiye', '2024-09-09');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Ayşe', 'Kaya', 'ayşe.kaya36@ornekmail.com', 'Adana', 'Türkiye', '2024-10-04');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Emre', 'Çelik', 'emre.çelik6@ornekmail.com', 'İstanbul', 'Türkiye', '2023-04-27');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Emre', 'Kaya', 'emre.kaya43@ornekmail.com', 'Gaziantep', 'Türkiye', '2024-06-21');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Emre', 'Doğan', 'emre.doğan68@ornekmail.com', 'Gaziantep', 'Türkiye', '2024-10-22');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Hüseyin', 'Kılıç', 'hüseyin.kılıç54@ornekmail.com', 'Adana', 'Türkiye', '2023-12-16');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Burak', 'Yıldız', 'burak.yıldız31@ornekmail.com', 'Konya', 'Türkiye', '2023-04-04');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Ahmet', 'Arslan', 'ahmet.arslan64@ornekmail.com', 'Gaziantep', 'Türkiye', '2023-03-23');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Ayşe', 'Arslan', 'ayşe.arslan97@ornekmail.com', 'Bursa', 'Türkiye', '2023-10-02');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Ali', 'Yıldız', 'ali.yıldız56@ornekmail.com', 'Konya', 'Türkiye', '2023-06-18');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Canan', 'Aydın', 'canan.aydın74@ornekmail.com', 'İzmir', 'Türkiye', '2023-06-27');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Ayşe', 'Kılıç', 'ayşe.kılıç45@ornekmail.com', 'Antalya', 'Türkiye', '2024-09-28');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Zeynep', 'Arslan', 'zeynep.arslan63@ornekmail.com', 'İstanbul', 'Türkiye', '2024-12-01');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Ahmet', 'Şahin', 'ahmet.şahin33@ornekmail.com', 'Ankara', 'Türkiye', '2023-12-11');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Fatma', 'Öztürk', 'fatma.öztürk14@ornekmail.com', 'Konya', 'Türkiye', '2024-09-27');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Elif', 'Arslan', 'elif.arslan78@ornekmail.com', 'Gaziantep', 'Türkiye', '2023-03-27');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Ali', 'Kılıç', 'ali.kılıç10@ornekmail.com', 'İstanbul', 'Türkiye', '2024-12-16');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Fatma', 'Özdemir', 'fatma.özdemir12@ornekmail.com', 'Gaziantep', 'Türkiye', '2023-03-01');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Emre', 'Doğan', 'emre.doğan76@ornekmail.com', 'Adana', 'Türkiye', '2024-07-24');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Selin', 'Doğan', 'selin.doğan46@ornekmail.com', 'Adana', 'Türkiye', '2024-09-17');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Elif', 'Özdemir', 'elif.özdemir34@ornekmail.com', 'Konya', 'Türkiye', '2024-06-06');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Hüseyin', 'Demir', 'hüseyin.demir14@ornekmail.com', 'Adana', 'Türkiye', '2023-02-09');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Ali', 'Kılıç', 'ali.kılıç98@ornekmail.com', 'Adana', 'Türkiye', '2023-12-03');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Ayşe', 'Kaya', 'ayşe.kaya72@ornekmail.com', 'İzmir', 'Türkiye', '2023-08-24');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Fatma', 'Çelik', 'fatma.çelik3@ornekmail.com', 'İstanbul', 'Türkiye', '2023-05-03');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Ali', 'Arslan', 'ali.arslan99@ornekmail.com', 'Ankara', 'Türkiye', '2023-02-15');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Ayşe', 'Doğan', 'ayşe.doğan49@ornekmail.com', 'İzmir', 'Türkiye', '2024-01-24');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Emre', 'Demir', 'emre.demir57@ornekmail.com', 'Adana', 'Türkiye', '2023-05-22');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Zeynep', 'Yılmaz', 'zeynep.yılmaz35@ornekmail.com', 'İstanbul', 'Türkiye', '2023-06-05');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Burak', 'Yılmaz', 'burak.yılmaz98@ornekmail.com', 'Konya', 'Türkiye', '2024-10-24');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Ali', 'Şahin', 'ali.şahin50@ornekmail.com', 'İzmir', 'Türkiye', '2023-02-26');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Mustafa', 'Özdemir', 'mustafa.özdemir82@ornekmail.com', 'Antalya', 'Türkiye', '2024-04-20');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Emre', 'Arslan', 'emre.arslan30@ornekmail.com', 'Antalya', 'Türkiye', '2024-06-11');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Mehmet', 'Yılmaz', 'mehmet.yılmaz19@ornekmail.com', 'Konya', 'Türkiye', '2024-11-02');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Selin', 'Yılmaz', 'selin.yılmaz78@ornekmail.com', 'Ankara', 'Türkiye', '2024-10-29');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Cem', 'Şahin', 'cem.şahin88@ornekmail.com', 'İzmir', 'Türkiye', '2024-10-17');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Ahmet', 'Yılmaz', 'ahmet.yılmaz43@ornekmail.com', 'Adana', 'Türkiye', '2024-06-26');
INSERT INTO Musteriler (ad, soyad, email, sehir, ulke, kayit_tarihi) VALUES ('Mustafa', 'Yıldız', 'mustafa.yıldız92@ornekmail.com', 'Adana', 'Türkiye', '2023-01-07');

-- Ürün Verileri
INSERT INTO Urunler (urun_adi, kategori_adi, alis_fiyati, satis_fiyati, stok_miktari) VALUES ('Laptop', 'Elektronik', 15000, 20000, 36);
INSERT INTO Urunler (urun_adi, kategori_adi, alis_fiyati, satis_fiyati, stok_miktari) VALUES ('Akıllı Telefon', 'Elektronik', 10000, 14000, 81);
INSERT INTO Urunler (urun_adi, kategori_adi, alis_fiyati, satis_fiyati, stok_miktari) VALUES ('Kulaklık', 'Elektronik', 500, 800, 35);
INSERT INTO Urunler (urun_adi, kategori_adi, alis_fiyati, satis_fiyati, stok_miktari) VALUES ('Tablet', 'Elektronik', 3000, 4500, 13);
INSERT INTO Urunler (urun_adi, kategori_adi, alis_fiyati, satis_fiyati, stok_miktari) VALUES ('T-Shirt', 'Giyim', 100, 250, 12);
INSERT INTO Urunler (urun_adi, kategori_adi, alis_fiyati, satis_fiyati, stok_miktari) VALUES ('Kot Pantolon', 'Giyim', 300, 600, 10);
INSERT INTO Urunler (urun_adi, kategori_adi, alis_fiyati, satis_fiyati, stok_miktari) VALUES ('Mont', 'Giyim', 800, 1500, 47);
INSERT INTO Urunler (urun_adi, kategori_adi, alis_fiyati, satis_fiyati, stok_miktari) VALUES ('Spor Ayakkabı', 'Giyim', 1200, 2000, 21);
INSERT INTO Urunler (urun_adi, kategori_adi, alis_fiyati, satis_fiyati, stok_miktari) VALUES ('Kahve Makinesi', 'Ev & Yaşam', 1500, 2500, 87);
INSERT INTO Urunler (urun_adi, kategori_adi, alis_fiyati, satis_fiyati, stok_miktari) VALUES ('Ütü', 'Ev & Yaşam', 800, 1200, 75);
INSERT INTO Urunler (urun_adi, kategori_adi, alis_fiyati, satis_fiyati, stok_miktari) VALUES ('Nevresim Takımı', 'Ev & Yaşam', 400, 700, 84);

-- Sipariş ve Detay Verileri
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (36, '2024-12-17', 'Aras Kargo', 'Kargoda');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (1, 5, 3, 250, 0.05);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (5, '2024-02-02', 'MNG Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (2, 11, 2, 700, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (2, 8, 1, 2000, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (2, 1, 2, 20000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (2, 4, 1, 4500, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (2, 10, 1, 1200, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (21, '2024-08-18', 'MNG Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (3, 4, 1, 4500, 0.1);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (43, '2025-07-11', 'Yurtiçi Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (4, 8, 2, 2000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (4, 10, 1, 1200, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (4, 3, 3, 800, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (4, 7, 3, 1500, 0.05);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (51, '2025-05-10', 'PTT Kargo', 'Kargoda');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (5, 4, 2, 4500, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (5, 1, 2, 20000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (5, 9, 3, 2500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (5, 7, 2, 1500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (5, 11, 3, 700, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (40, '2024-02-22', 'Aras Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (6, 5, 1, 250, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (6, 9, 2, 2500, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (6, 4, 3, 4500, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (6, 2, 3, 14000, 0.05);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (59, '2025-10-11', 'PTT Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (7, 6, 1, 600, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (7, 1, 2, 20000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (7, 2, 3, 14000, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (7, 9, 2, 2500, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (35, '2024-08-16', 'PTT Kargo', 'Hazırlanıyor');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (8, 8, 2, 2000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (8, 1, 1, 20000, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (8, 7, 2, 1500, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (8, 11, 1, 700, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (8, 10, 1, 1200, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (27, '2024-03-04', 'Yurtiçi Kargo', 'İptal');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (9, 2, 3, 14000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (9, 7, 3, 1500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (9, 3, 3, 800, 0.05);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (37, '2025-03-04', 'Aras Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (10, 4, 1, 4500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (10, 1, 2, 20000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (10, 7, 1, 1500, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (10, 10, 2, 1200, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (7, '2024-04-23', 'Yurtiçi Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (11, 8, 3, 2000, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (11, 9, 1, 2500, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (11, 7, 2, 1500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (11, 1, 2, 20000, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (16, '2025-04-30', 'PTT Kargo', 'Hazırlanıyor');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (12, 7, 3, 1500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (12, 11, 1, 700, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (12, 8, 1, 2000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (12, 4, 3, 4500, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (16, '2025-11-14', 'Yurtiçi Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (13, 8, 1, 2000, 0.05);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (38, '2025-06-25', 'MNG Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (14, 9, 3, 2500, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (5, '2025-02-08', 'PTT Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (15, 9, 2, 2500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (15, 5, 1, 250, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (15, 1, 2, 20000, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (1, '2024-05-24', 'PTT Kargo', 'Hazırlanıyor');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (16, 11, 3, 700, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (37, '2025-07-14', 'MNG Kargo', 'İptal');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (17, 4, 3, 4500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (17, 8, 2, 2000, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (3, '2025-03-30', 'MNG Kargo', 'Kargoda');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (18, 2, 2, 14000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (18, 10, 1, 1200, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (18, 5, 3, 250, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (18, 4, 1, 4500, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (37, '2025-12-16', 'Yurtiçi Kargo', 'İptal');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (19, 10, 3, 1200, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (19, 5, 1, 250, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (19, 8, 3, 2000, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (19, 11, 3, 700, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (10, '2024-12-23', 'MNG Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (20, 4, 3, 4500, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (51, '2024-05-03', 'PTT Kargo', 'İptal');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (21, 4, 2, 4500, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (40, '2024-05-18', 'MNG Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (22, 3, 1, 800, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (56, '2024-10-13', 'Aras Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (23, 2, 3, 14000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (23, 4, 3, 4500, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (7, '2024-09-22', 'Yurtiçi Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (24, 8, 1, 2000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (24, 2, 1, 14000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (24, 11, 1, 700, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (24, 1, 2, 20000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (24, 9, 2, 2500, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (11, '2024-11-05', 'PTT Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (25, 5, 1, 250, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (25, 9, 2, 2500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (25, 7, 1, 1500, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (28, '2025-11-21', 'Aras Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (26, 7, 3, 1500, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (26, 11, 3, 700, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (6, '2025-12-27', 'MNG Kargo', 'Hazırlanıyor');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (27, 9, 1, 2500, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (29, '2024-11-15', 'PTT Kargo', 'İptal');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (28, 4, 1, 4500, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (28, 6, 2, 600, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (28, 1, 1, 20000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (28, 5, 1, 250, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (24, '2024-01-11', 'Aras Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (29, 8, 2, 2000, 0.05);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (18, '2024-12-15', 'PTT Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (30, 6, 2, 600, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (30, 5, 3, 250, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (30, 3, 2, 800, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (30, 1, 3, 20000, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (40, '2025-04-11', 'PTT Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (31, 6, 3, 600, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (16, '2025-09-29', 'MNG Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (32, 5, 1, 250, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (57, '2024-11-13', 'PTT Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (33, 6, 3, 600, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (33, 11, 2, 700, 0.1);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (35, '2024-03-08', 'MNG Kargo', 'Kargoda');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (34, 9, 2, 2500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (34, 1, 3, 20000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (34, 8, 3, 2000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (34, 4, 3, 4500, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (46, '2024-05-25', 'Aras Kargo', 'Kargoda');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (35, 3, 3, 800, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (35, 4, 2, 4500, 0.1);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (42, '2025-10-03', 'MNG Kargo', 'Hazırlanıyor');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (36, 10, 2, 1200, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (36, 2, 1, 14000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (36, 9, 2, 2500, 0.05);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (50, '2024-06-06', 'MNG Kargo', 'Kargoda');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (37, 9, 3, 2500, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (37, 2, 2, 14000, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (37, 10, 1, 1200, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (37, 11, 1, 700, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (37, 5, 3, 250, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (26, '2025-10-02', 'Yurtiçi Kargo', 'İptal');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (38, 7, 2, 1500, 0.1);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (58, '2024-05-03', 'PTT Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (39, 3, 2, 800, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (39, 7, 1, 1500, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (42, '2025-12-05', 'MNG Kargo', 'Hazırlanıyor');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (40, 8, 3, 2000, 0.1);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (21, '2024-07-15', 'Aras Kargo', 'Kargoda');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (41, 1, 3, 20000, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (41, 7, 1, 1500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (41, 4, 1, 4500, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (44, '2025-07-27', 'MNG Kargo', 'Hazırlanıyor');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (42, 4, 1, 4500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (42, 6, 2, 600, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (32, '2024-08-11', 'Aras Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (43, 4, 2, 4500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (43, 3, 1, 800, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (43, 6, 3, 600, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (43, 7, 1, 1500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (43, 2, 3, 14000, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (43, '2025-07-15', 'Aras Kargo', 'İptal');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (44, 4, 2, 4500, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (35, '2025-12-27', 'PTT Kargo', 'Hazırlanıyor');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (45, 1, 1, 20000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (45, 10, 1, 1200, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (45, 6, 2, 600, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (36, '2024-08-27', 'Yurtiçi Kargo', 'İptal');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (46, 7, 2, 1500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (46, 5, 2, 250, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (46, 3, 1, 800, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (11, '2024-06-16', 'Aras Kargo', 'Hazırlanıyor');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (47, 2, 3, 14000, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (47, 7, 3, 1500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (47, 1, 2, 20000, 0.05);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (44, '2025-04-16', 'Aras Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (48, 11, 3, 700, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (48, 2, 3, 14000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (48, 4, 1, 4500, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (13, '2025-08-14', 'MNG Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (49, 11, 2, 700, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (49, 3, 1, 800, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (49, 6, 1, 600, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (49, 9, 3, 2500, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (49, 10, 2, 1200, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (6, '2024-03-18', 'MNG Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (50, 10, 1, 1200, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (50, 1, 2, 20000, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (50, 6, 1, 600, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (47, '2025-02-10', 'MNG Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (51, 6, 2, 600, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (23, '2024-03-26', 'PTT Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (52, 4, 1, 4500, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (52, 8, 1, 2000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (52, 2, 2, 14000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (52, 10, 3, 1200, 0.1);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (20, '2024-08-28', 'Yurtiçi Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (53, 5, 1, 250, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (53, 4, 1, 4500, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (53, 10, 1, 1200, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (53, 1, 3, 20000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (53, 3, 1, 800, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (5, '2025-07-20', 'PTT Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (54, 7, 2, 1500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (54, 10, 1, 1200, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (47, '2024-11-08', 'Aras Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (55, 2, 2, 14000, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (22, '2025-05-27', 'PTT Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (56, 3, 2, 800, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (56, 6, 1, 600, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (56, 10, 1, 1200, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (56, 5, 3, 250, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (56, 4, 3, 4500, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (22, '2025-02-12', 'PTT Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (57, 9, 3, 2500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (57, 6, 2, 600, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (57, 10, 2, 1200, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (57, 4, 2, 4500, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (3, '2025-06-20', 'PTT Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (58, 3, 1, 800, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (58, 10, 3, 1200, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (58, 7, 2, 1500, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (15, '2024-04-13', 'Aras Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (59, 6, 2, 600, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (59, 3, 1, 800, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (59, 11, 1, 700, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (34, '2025-04-09', 'Aras Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (60, 8, 1, 2000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (60, 1, 3, 20000, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (21, '2024-10-30', 'Aras Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (61, 5, 1, 250, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (61, 10, 2, 1200, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (15, '2025-10-22', 'Aras Kargo', 'Kargoda');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (62, 8, 1, 2000, 0.05);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (43, '2025-10-05', 'PTT Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (63, 6, 2, 600, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (63, 4, 2, 4500, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (35, '2024-10-10', 'MNG Kargo', 'Kargoda');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (64, 6, 1, 600, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (64, 10, 3, 1200, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (64, 5, 1, 250, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (49, '2025-09-27', 'Yurtiçi Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (65, 10, 1, 1200, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (65, 6, 1, 600, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (26, '2025-09-14', 'PTT Kargo', 'Kargoda');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (66, 7, 3, 1500, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (15, '2024-03-06', 'PTT Kargo', 'İptal');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (67, 7, 1, 1500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (67, 2, 3, 14000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (67, 5, 3, 250, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (67, 10, 2, 1200, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (67, 3, 1, 800, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (2, '2025-06-12', 'Yurtiçi Kargo', 'İptal');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (68, 11, 3, 700, 0.1);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (11, '2024-09-29', 'MNG Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (69, 3, 2, 800, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (69, 6, 3, 600, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (2, '2025-10-14', 'PTT Kargo', 'Hazırlanıyor');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (70, 1, 3, 20000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (70, 9, 3, 2500, 0.05);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (59, '2024-12-24', 'PTT Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (71, 5, 3, 250, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (71, 7, 1, 1500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (71, 10, 2, 1200, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (71, 4, 2, 4500, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (71, 2, 3, 14000, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (17, '2024-02-06', 'Aras Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (72, 11, 3, 700, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (72, 1, 2, 20000, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (72, 7, 2, 1500, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (16, '2025-05-27', 'PTT Kargo', 'İptal');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (73, 5, 3, 250, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (73, 9, 1, 2500, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (73, 7, 2, 1500, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (73, 4, 1, 4500, 0.05);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (59, '2025-08-07', 'PTT Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (74, 2, 2, 14000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (74, 7, 2, 1500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (74, 4, 1, 4500, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (74, 3, 1, 800, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (42, '2024-10-17', 'MNG Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (75, 7, 2, 1500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (75, 9, 2, 2500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (75, 6, 1, 600, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (75, 1, 1, 20000, 0.05);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (7, '2024-10-10', 'MNG Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (76, 1, 3, 20000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (76, 3, 3, 800, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (59, '2024-09-27', 'Aras Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (77, 8, 2, 2000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (77, 5, 1, 250, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (77, 11, 1, 700, 0.05);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (20, '2025-10-18', 'PTT Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (78, 9, 3, 2500, 0.1);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (12, '2025-03-13', 'Aras Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (79, 5, 2, 250, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (79, 9, 1, 2500, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (60, '2024-11-24', 'MNG Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (80, 11, 2, 700, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (80, 10, 2, 1200, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (80, 3, 3, 800, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (80, 1, 1, 20000, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (16, '2025-08-01', 'Aras Kargo', 'Kargoda');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (81, 3, 2, 800, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (81, 9, 3, 2500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (81, 11, 1, 700, 0.05);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (18, '2025-08-19', 'Aras Kargo', 'İptal');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (82, 4, 1, 4500, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (82, 9, 3, 2500, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (82, 10, 3, 1200, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (82, 2, 2, 14000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (82, 3, 2, 800, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (35, '2025-09-19', 'Aras Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (83, 8, 3, 2000, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (83, 6, 1, 600, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (83, 1, 2, 20000, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (43, '2024-06-27', 'Aras Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (84, 7, 3, 1500, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (84, 3, 2, 800, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (84, 9, 1, 2500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (84, 4, 2, 4500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (84, 10, 1, 1200, 0.1);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (9, '2025-11-22', 'PTT Kargo', 'İptal');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (85, 3, 1, 800, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (85, 10, 1, 1200, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (85, 4, 1, 4500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (85, 5, 1, 250, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (9, '2025-06-30', 'Aras Kargo', 'Hazırlanıyor');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (86, 6, 3, 600, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (86, 3, 2, 800, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (86, 2, 2, 14000, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (86, 11, 2, 700, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (86, 8, 2, 2000, 0.1);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (25, '2025-11-14', 'Yurtiçi Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (87, 8, 3, 2000, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (36, '2024-08-08', 'Yurtiçi Kargo', 'Hazırlanıyor');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (88, 5, 1, 250, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (88, 2, 2, 14000, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (88, 10, 1, 1200, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (88, 4, 3, 4500, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (88, 3, 3, 800, 0.1);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (59, '2024-11-21', 'Yurtiçi Kargo', 'Hazırlanıyor');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (89, 1, 1, 20000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (89, 6, 3, 600, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (89, 5, 1, 250, 0.05);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (52, '2025-02-25', 'Yurtiçi Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (90, 3, 2, 800, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (90, 7, 1, 1500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (90, 6, 2, 600, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (90, 9, 2, 2500, 0.05);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (38, '2025-05-12', 'MNG Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (91, 11, 1, 700, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (91, 4, 1, 4500, 0.05);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (8, '2024-10-13', 'MNG Kargo', 'İptal');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (92, 2, 3, 14000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (92, 5, 1, 250, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (92, 11, 3, 700, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (92, 3, 1, 800, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (92, 1, 2, 20000, 0.05);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (24, '2024-09-21', 'Yurtiçi Kargo', 'Hazırlanıyor');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (93, 3, 3, 800, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (93, 4, 1, 4500, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (93, 5, 2, 250, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (23, '2025-07-09', 'PTT Kargo', 'Kargoda');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (94, 6, 1, 600, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (55, '2025-08-29', 'Aras Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (95, 9, 2, 2500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (95, 3, 1, 800, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (95, 6, 2, 600, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (95, 8, 3, 2000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (95, 10, 1, 1200, 0.05);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (39, '2025-07-01', 'MNG Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (96, 7, 1, 1500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (96, 9, 2, 2500, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (47, '2024-08-05', 'MNG Kargo', 'Kargoda');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (97, 11, 3, 700, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (97, 7, 2, 1500, 0.05);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (17, '2024-09-03', 'Yurtiçi Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (98, 8, 1, 2000, 0.05);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (34, '2024-01-21', 'PTT Kargo', 'Kargoda');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (99, 7, 1, 1500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (99, 11, 1, 700, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (99, 2, 1, 14000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (99, 9, 2, 2500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (99, 4, 3, 4500, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (54, '2024-10-23', 'PTT Kargo', 'Hazırlanıyor');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (100, 1, 3, 20000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (100, 2, 1, 14000, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (100, 11, 2, 700, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (100, 7, 1, 1500, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (3, '2025-06-15', 'MNG Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (101, 8, 1, 2000, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (51, '2025-02-06', 'PTT Kargo', 'İptal');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (102, 8, 1, 2000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (102, 11, 3, 700, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (102, 7, 2, 1500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (102, 9, 3, 2500, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (3, '2025-05-30', 'PTT Kargo', 'Hazırlanıyor');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (103, 1, 3, 20000, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (103, 5, 2, 250, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (103, 10, 3, 1200, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (103, 2, 2, 14000, 0.1);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (2, '2024-07-10', 'Aras Kargo', 'İptal');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (104, 2, 2, 14000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (104, 6, 2, 600, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (104, 9, 2, 2500, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (37, '2025-01-03', 'Yurtiçi Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (105, 9, 2, 2500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (105, 3, 3, 800, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (105, 10, 3, 1200, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (105, 11, 2, 700, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (27, '2025-02-09', 'Aras Kargo', 'Kargoda');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (106, 2, 1, 14000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (106, 11, 2, 700, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (106, 3, 3, 800, 0.1);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (45, '2025-04-16', 'Aras Kargo', 'Kargoda');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (107, 1, 2, 20000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (107, 9, 2, 2500, 0.05);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (53, '2025-10-12', 'Yurtiçi Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (108, 6, 1, 600, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (108, 5, 1, 250, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (108, 2, 3, 14000, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (39, '2024-12-22', 'Yurtiçi Kargo', 'Hazırlanıyor');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (109, 3, 1, 800, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (43, '2025-05-17', 'Yurtiçi Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (110, 4, 2, 4500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (110, 6, 3, 600, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (110, 9, 3, 2500, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (110, 3, 2, 800, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (110, 7, 3, 1500, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (50, '2024-01-10', 'PTT Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (111, 11, 3, 700, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (111, 5, 3, 250, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (111, 9, 2, 2500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (111, 4, 3, 4500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (111, 1, 3, 20000, 0.1);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (49, '2024-01-20', 'PTT Kargo', 'Hazırlanıyor');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (112, 1, 2, 20000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (112, 9, 2, 2500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (112, 10, 1, 1200, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (112, 4, 2, 4500, 0.1);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (18, '2024-12-31', 'MNG Kargo', 'Kargoda');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (113, 5, 1, 250, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (113, 2, 3, 14000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (113, 7, 2, 1500, 0.1);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (14, '2024-12-29', 'MNG Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (114, 11, 1, 700, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (114, 5, 3, 250, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (114, 3, 3, 800, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (22, '2025-02-04', 'Yurtiçi Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (115, 9, 3, 2500, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (115, 2, 1, 14000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (115, 6, 2, 600, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (115, 8, 2, 2000, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (54, '2025-12-18', 'MNG Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (116, 10, 3, 1200, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (116, 8, 2, 2000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (116, 2, 3, 14000, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (116, 3, 3, 800, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (116, 9, 3, 2500, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (40, '2024-01-22', 'MNG Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (117, 5, 1, 250, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (117, 1, 2, 20000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (117, 8, 1, 2000, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (117, 3, 3, 800, 0.1);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (45, '2025-06-22', 'PTT Kargo', 'Hazırlanıyor');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (118, 3, 2, 800, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (118, 7, 3, 1500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (118, 11, 2, 700, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (118, 8, 1, 2000, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (51, '2024-04-01', 'PTT Kargo', 'Kargoda');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (119, 9, 3, 2500, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (119, 10, 3, 1200, 0.1);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (54, '2025-04-05', 'PTT Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (120, 4, 1, 4500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (120, 3, 1, 800, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (18, '2025-05-18', 'Aras Kargo', 'Hazırlanıyor');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (121, 10, 1, 1200, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (121, 5, 1, 250, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (121, 11, 2, 700, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (121, 8, 3, 2000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (121, 4, 1, 4500, 0.1);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (26, '2025-11-21', 'Aras Kargo', 'İptal');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (122, 9, 3, 2500, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (122, 2, 1, 14000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (122, 7, 1, 1500, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (122, 4, 2, 4500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (122, 11, 2, 700, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (47, '2025-04-15', 'PTT Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (123, 7, 3, 1500, 0.1);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (19, '2024-05-29', 'Yurtiçi Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (124, 7, 1, 1500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (124, 11, 3, 700, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (124, 9, 1, 2500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (124, 5, 1, 250, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (22, '2024-02-25', 'Aras Kargo', 'Hazırlanıyor');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (125, 3, 2, 800, 0.05);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (52, '2025-03-01', 'Yurtiçi Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (126, 3, 1, 800, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (126, 5, 3, 250, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (126, 9, 3, 2500, 0.1);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (18, '2024-12-22', 'MNG Kargo', 'İptal');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (127, 6, 2, 600, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (127, 10, 1, 1200, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (127, 5, 3, 250, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (56, '2024-10-07', 'Aras Kargo', 'Hazırlanıyor');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (128, 1, 1, 20000, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (128, 7, 1, 1500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (128, 2, 3, 14000, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (13, '2024-06-24', 'Yurtiçi Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (129, 1, 1, 20000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (129, 2, 2, 14000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (129, 11, 3, 700, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (42, '2024-07-20', 'Yurtiçi Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (130, 11, 2, 700, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (130, 3, 3, 800, 0.05);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (5, '2025-04-15', 'Aras Kargo', 'İptal');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (131, 1, 3, 20000, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (131, 3, 2, 800, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (131, 5, 1, 250, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (10, '2025-04-24', 'MNG Kargo', 'Hazırlanıyor');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (132, 9, 2, 2500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (132, 4, 3, 4500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (132, 8, 2, 2000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (132, 7, 2, 1500, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (132, 1, 2, 20000, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (19, '2025-04-14', 'PTT Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (133, 9, 2, 2500, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (133, 8, 2, 2000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (133, 5, 3, 250, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (133, 2, 3, 14000, 0.1);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (60, '2024-12-28', 'Yurtiçi Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (134, 2, 3, 14000, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (134, 5, 3, 250, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (38, '2025-09-09', 'PTT Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (135, 4, 3, 4500, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (135, 10, 3, 1200, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (135, 1, 2, 20000, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (29, '2024-09-29', 'Yurtiçi Kargo', 'Hazırlanıyor');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (136, 7, 1, 1500, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (136, 10, 2, 1200, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (136, 6, 1, 600, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (136, 9, 3, 2500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (136, 8, 2, 2000, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (12, '2025-11-12', 'Aras Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (137, 2, 1, 14000, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (55, '2025-01-18', 'MNG Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (138, 5, 2, 250, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (138, 2, 3, 14000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (138, 7, 3, 1500, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (138, 1, 1, 20000, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (40, '2024-02-23', 'Aras Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (139, 11, 2, 700, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (24, '2025-02-11', 'MNG Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (140, 6, 3, 600, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (140, 1, 3, 20000, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (26, '2024-09-17', 'PTT Kargo', 'İptal');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (141, 11, 3, 700, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (141, 10, 3, 1200, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (141, 8, 1, 2000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (141, 7, 3, 1500, 0.05);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (12, '2024-08-10', 'Yurtiçi Kargo', 'Kargoda');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (142, 1, 3, 20000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (142, 9, 1, 2500, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (142, 11, 2, 700, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (142, 3, 2, 800, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (24, '2025-08-05', 'PTT Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (143, 3, 1, 800, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (143, 8, 1, 2000, 0.1);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (58, '2025-04-06', 'Yurtiçi Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (144, 9, 1, 2500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (144, 2, 3, 14000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (144, 11, 2, 700, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (144, 1, 3, 20000, 0.1);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (52, '2024-07-25', 'PTT Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (145, 5, 1, 250, 0.1);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (46, '2025-11-28', 'MNG Kargo', 'Hazırlanıyor');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (146, 8, 3, 2000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (146, 5, 1, 250, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (146, 3, 1, 800, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (146, 11, 3, 700, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (146, 2, 3, 14000, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (6, '2024-11-28', 'Aras Kargo', 'Kargoda');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (147, 7, 1, 1500, 0.05);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (47, '2024-02-23', 'MNG Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (148, 9, 3, 2500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (148, 7, 2, 1500, 0.05);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (148, 10, 1, 1200, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (148, 11, 1, 700, 0.0);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (34, '2024-07-11', 'MNG Kargo', 'Teslim Edildi');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (149, 2, 3, 14000, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (149, 5, 1, 250, 0.1);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (149, 1, 2, 20000, 0.05);
INSERT INTO Siparisler (musteri_id, siparis_tarihi, kargo_firmasi, durum) VALUES (5, '2025-07-31', 'Aras Kargo', 'İptal');
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (150, 1, 2, 20000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (150, 8, 3, 2000, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (150, 7, 1, 1500, 0.0);
INSERT INTO Siparis_Detay (siparis_id, urun_id, miktar, birim_fiyat, indirim_orani) VALUES (150, 3, 1, 800, 0.0);